spring:
  security:
    oauth2:
      client:
        registration:
          github:
            # The client ID for GitHub OAuth2, encrypted using Jasypt
            client-id: ENC(your-encrypted-github-client-id)
            # The client secret for GitHub OAuth2, encrypted using Jasypt
            client-secret: ENC(your-encrypted-github-client-secret)
          google:
            # The client ID for Google OAuth2, encrypted using Jasypt
            client-id: ENC(your-encrypted-google-client-id)
            # The client secret for Google OAuth2, encrypted using Jasypt
            client-secret: ENC(your-encrypted-google-client-secret)
jasypt:
  encryptor:
    # The password used to decrypt encrypted values, can be set as an environment variable or default to 'changeit'
    password: ${JASYPT_ENCRYPTOR_PASSWORD:changeit}
    # Specifies the encryption algorithm used, in this case PBEWithMD5AndDES
    algorithm: PBEWithMD5AndDES
    # No IV (Initialization Vector) is used for this encryption setup
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
logging:
  level:
    org.springframework.security:
      # Sets the logging level for Spring Security to TRACE for detailed debugging information
      TRACE
